/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_feidao_jni_One_1 */

#ifndef _Included_com_feidao_jni_One_1
#define _Included_com_feidao_jni_One_1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_feidao_jni_One_1
 * Method:    getStrFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_feidao_jni_One_11_getStrFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
