/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_feidao_ndk_jni_Two */

#ifndef _Included_com_feidao_ndk_jni_Two
#define _Included_com_feidao_ndk_jni_Two
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_feidao_ndk_jni_Two
 * Method:    getStrFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_feidao_ndk_jni_Two_getStrFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
